# Stage 1: Build the React app
FROM node:18-alpine as build
WORKDIR /app
COPY GrocerSaveWeb/package*.json ./
RUN npm install
COPY GrocerSaveWeb/ .
RUN npm run build

# Stage 2: Serve the static files with a plain Nginx
FROM nginx:alpine
# Copy the built static files from the build stage
COPY --from=build /app/build /usr/share/nginx/html
# Nginx will automatically serve index.html for any directory requests
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]