FROM node:20-alpine
WORKDIR /app

# Install curl for debugging
RUN apk add --no-cache curl

COPY Services/bff-service/package*.json ./
RUN npm install
COPY Services/bff-service/ .
EXPOSE 3100
CMD ["node", "index.js"]