-- Drop the table to ensure a clean slate with the new schema
DROP TABLE IF EXISTS products;

-- Create the table with the new 'category' column
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  category TEXT
);

-- Insert sample product data using stable, direct image URLs of actual food
INSERT INTO products (name, description, image_url, category) VALUES
('Organic Milk', '2L of organic whole milk from a local farm.', 'https://www.themealdb.com/images/ingredients/Milk.png', 'Dairy & Eggs'),
('Free-Range Eggs', 'One dozen large brown free-range eggs.', 'https://www.themealdb.com/images/ingredients/Eggs.png', 'Dairy & Eggs'),
('Sourdough Bread', 'Freshly baked artisan sourdough loaf.', 'https://www.themealdb.com/images/ingredients/Bread.png', 'Bakery'),
('Avocados', 'Bag of 5 ripe Hass avocados.', 'https://www.themealdb.com/images/ingredients/Avocado.png', 'Produce'),
('Chicken Breast', '1kg of skinless, boneless chicken breast.', 'https://www.themealdb.com/images/ingredients/Chicken.png', 'Meat & Seafood'),
('Salmon Fillet', '500g of fresh Atlantic salmon fillet.', 'https://www.themealdb.com/images/ingredients/Salmon.png', 'Meat & Seafood'),
('Organic Apples', 'Bag of 6 organic Gala apples.', 'https://www.themealdb.com/images/ingredients/Apples.png', 'Produce'),
('Greek Yogurt', '500g tub of plain Greek yogurt.', 'https://www.themealdb.com/images/ingredients/Yogurt.png', 'Dairy & Eggs'),
('Quinoa', '1kg bag of organic white quinoa.', 'https://www.themealdb.com/images/ingredients/Quinoa.png', 'Pantry'),
('Almond Milk', '1L carton of unsweetened almond milk.', 'https://www.themealdb.com/images/ingredients/Milk.png', 'Pantry'),
('Organic Carrots', '1kg bag of organic carrots.', 'https://www.themealdb.com/images/ingredients/Carrots.png', 'Produce'),
('Whole Wheat Pasta', '500g pack of whole wheat fusilli.', 'https://www.themealdb.com/images/ingredients/Pasta.png', 'Pantry'),
('Cheddar Cheese', '250g block of mature cheddar cheese.', 'https://www.themealdb.com/images/ingredients/Cheese.png', 'Dairy & Eggs'),
('Tomatoes', '500g of ripe vine tomatoes.', 'https://www.themealdb.com/images/ingredients/Tomato.png', 'Produce'),
('Ground Beef', '500g of lean ground beef.', 'https://www.themealdb.com/images/ingredients/Beef.png', 'Meat & Seafood'),
('Bananas', 'Bunch of 5 organic bananas.', 'https://www.themealdb.com/images/ingredients/Banana.png', 'Produce'),
('Spinach', '200g bag of fresh spinach.', 'https://www.themealdb.com/images/ingredients/Spinach.png', 'Produce'),
('Oats', '1kg bag of rolled oats.', 'https://www.themealdb.com/images/ingredients/Oats.png', 'Pantry'),
('Blueberries', '150g punnet of fresh blueberries.', 'https://www.themealdb.com/images/ingredients/Blueberries.png', 'Produce'),
('Canned Tuna', 'Can of tuna chunks in spring water.', 'https://www.themealdb.com/images/ingredients/Tuna.png', 'Pantry'),
('Potatoes', '2kg bag of white potatoes.', 'https://www.themealdb.com/images/ingredients/Potatoes.png', 'Produce'),
('Onions', '1kg bag of brown onions.', 'https://www.themealdb.com/images/ingredients/Onion.png', 'Produce'),
('Garlic', '3 bulbs of fresh garlic.', 'https://www.themealdb.com/images/ingredients/Garlic.png', 'Produce'),
('Cucumber', 'Single large cucumber.', 'https://www.themealdb.com/images/ingredients/Cucumber.png', 'Produce'),
('Bell Peppers', 'Pack of 3 mixed bell peppers.', 'https://www.themealdb.com/images/ingredients/Red%20Pepper.png', 'Produce'),
('Broccoli', 'Head of fresh broccoli.', 'https://www.themealdb.com/images/ingredients/Broccoli.png', 'Produce'),
('Lettuce', 'Head of iceberg lettuce.', 'https://www.themealdb.com/images/ingredients/Lettuce.png', 'Produce'),
('Mushrooms', '250g of closed cup mushrooms.', 'https://www.themealdb.com/images/ingredients/Mushrooms.png', 'Produce'),
('Orange Juice', '1L carton of fresh orange juice.', 'https://www.themealdb.com/images/ingredients/Orange.png', 'Beverages'),
('Butter', '250g block of unsalted butter.', 'https://www.themealdb.com/images/ingredients/Butter.png', 'Dairy & Eggs'),
('White Bread', 'Loaf of sliced white bread.', 'https://www.themealdb.com/images/ingredients/Bread.png', 'Bakery'),
('Rice', '1kg bag of long-grain white rice.', 'https://www.themealdb.com/images/ingredients/Rice.png', 'Pantry'),
('Lentils', '500g bag of green lentils.', 'https://www.themealdb.com/images/ingredients/Lentils.png', 'Pantry'),
('Chickpeas', 'Can of chickpeas in water.', 'https://www.themealdb.com/images/ingredients/Chickpeas.png', 'Pantry'),
('Peanut Butter', '500g jar of smooth peanut butter.', 'https://www.themealdb.com/images/ingredients/Peanut%20Butter.png', 'Pantry'),
('Jam', 'Jar of strawberry jam.', 'https://www.themealdb.com/images/ingredients/Jam.png', 'Pantry'),
('Honey', 'Jar of clear honey.', 'https://www.themealdb.com/images/ingredients/Honey.png', 'Pantry'),
('Coffee', '250g bag of ground coffee.', 'https://www.themealdb.com/images/ingredients/Coffee.png', 'Beverages'),
('Tea Bags', 'Box of 100 black tea bags.', 'https://www.themealdb.com/images/ingredients/Tea.png', 'Beverages'),
('Sugar', '1kg bag of granulated sugar.', 'https://www.themealdb.com/images/ingredients/Sugar.png', 'Pantry'),
('Flour', '1.5kg bag of plain flour.', 'https://www.themealdb.com/images/ingredients/Flour.png', 'Pantry'),
('Olive Oil', '500ml bottle of extra virgin olive oil.', 'https://www.themealdb.com/images/ingredients/Olive%20Oil.png', 'Pantry'),
('Vinegar', '500ml bottle of white wine vinegar.', 'https://www.themealdb.com/images/ingredients/Vinegar.png', 'Pantry'),
('Salt', '750g tub of table salt.', 'https://www.themealdb.com/images/ingredients/Salt.png', 'Pantry'),
('Black Pepper', '50g grinder of black peppercorns.', 'https://www.themealdb.com/images/ingredients/Pepper.png', 'Pantry'),
('Herbs', 'Jar of mixed dried herbs.', 'https://www.themealdb.com/images/ingredients/Basil.png', 'Pantry'),
('Spices', 'Jar of paprika.', 'https://www.themealdb.com/images/ingredients/Paprika.png', 'Pantry'),
('Chocolate', '100g bar of dark chocolate.', 'https://www.themealdb.com/images/ingredients/Dark%20Chocolate.png', 'Snacks'),
('Biscuits', 'Pack of digestive biscuits.', 'https://www.themealdb.com/images/ingredients/Biscuits.png', 'Snacks'),
('Crisps', 'Bag of ready salted crisps.', 'https://www.themealdb.com/images/ingredients/Potatoes.png', 'Snacks'),
('Soda', 'Can of cola.', 'https://www.themealdb.com/images/ingredients/Water.png', 'Beverages'),
('Beer', 'Bottle of lager.', 'https://www.themealdb.com/images/ingredients/Beer.png', 'Beverages'),
('Wine', 'Bottle of red wine.', 'https://www.themealdb.com/images/ingredients/Wine.png', 'Beverages'),
('Cereal', 'Box of corn flakes.', 'https://www.themealdb.com/images/ingredients/Oats.png', 'Pantry'),
('Ice Cream', 'Tub of vanilla ice cream.', 'https://www.themealdb.com/images/ingredients/Ice%20Cream.png', 'Frozen'),
('Pizza', 'Frozen margherita pizza.', 'https://www.themealdb.com/images/ingredients/Pizza.png', 'Frozen'),
('Yogurt Drinks', 'Pack of 4 strawberry yogurt drinks.', 'https://www.themealdb.com/images/ingredients/Yogurt.png', 'Dairy & Eggs'),
('Tofu', '300g block of firm tofu.', 'https://www.themealdb.com/images/ingredients/Tofu.png', 'Pantry'),
('Nuts', 'Bag of mixed nuts.', 'https://www.themealdb.com/images/ingredients/Almonds.png', 'Snacks'),
('Dried Fruit', 'Bag of mixed dried fruit.', 'https://www.themealdb.com/images/ingredients/Dates.png', 'Snacks'),
('Protein Bar', 'Chocolate flavour protein bar.', 'https://www.themealdb.com/images/ingredients/Chocolate.png', 'Snacks'),
('Ketchup', 'Bottle of tomato ketchup.', 'https://www.themealdb.com/images/ingredients/Tomato%20Puree.png', 'Pantry'),
('Mayonnaise', 'Jar of mayonnaise.', 'https://www.themealdb.com/images/ingredients/Mayonnaise.png', 'Pantry'),
('Mustard', 'Jar of English mustard.', 'https://www.themealdb.com/images/ingredients/Mustard.png', 'Pantry'),
('Salsa', 'Jar of mild salsa.', 'https://www.themealdb.com/images/ingredients/Tomato.png', 'Pantry'),
('Tortilla Chips', 'Bag of salted tortilla chips.', 'https://www.themealdb.com/images/ingredients/Tortillas.png', 'Snacks'),
('Wraps', 'Pack of 8 tortilla wraps.', 'https://www.themealdb.com/images/ingredients/Tortillas.png', 'Bakery'),
('Bagels', 'Pack of 4 plain bagels.', 'https://www.themealdb.com/images/ingredients/Bread.png', 'Bakery'),
('Croissants', 'Pack of 2 all-butter croissants.', 'https://www.themealdb.com/images/ingredients/Croissants.png', 'Bakery'),
('Muffins', 'Pack of 4 blueberry muffins.', 'https://www.themealdb.com/images/ingredients/Muffins.png', 'Bakery'),
('Doughnuts', 'Pack of 4 glazed ring doughnuts.', 'https://www.themealdb.com/images/ingredients/Sugar.png', 'Bakery'),
('Pancakes', 'Pack of 6 ready-made pancakes.', 'https://www.themealdb.com/images/ingredients/Pancakes.png', 'Bakery'),
('Waffles', 'Pack of 4 frozen waffles.', 'https://www.themealdb.com/images/ingredients/Pancakes.png', 'Frozen'),
('Syrup', 'Bottle of maple syrup.', 'https://www.themealdb.com/images/ingredients/Maple%20Syrup.png', 'Pantry'),
('Couscous', 'Box of instant couscous.', 'https://www.themealdb.com/images/ingredients/Couscous.png', 'Pantry'),
('Noodles', 'Pack of instant noodles.', 'https://www.themealdb.com/images/ingredients/Noodles.png', 'Pantry'),
('Soy Sauce', 'Bottle of light soy sauce.', 'https://www.themealdb.com/images/ingredients/Soy%20Sauce.png', 'Pantry'),
('Sweet Chilli Sauce', 'Bottle of sweet chilli sauce.', 'https://www.themealdb.com/images/ingredients/Chilli.png', 'Pantry'),
('Coconut Milk', 'Can of coconut milk.', 'https://www.themealdb.com/images/ingredients/Coconut%20Milk.png', 'Pantry'),
('Curry Paste', 'Jar of red Thai curry paste.', 'https://www.themealdb.com/images/ingredients/Curry.png', 'Pantry'),
('Stock Cubes', 'Box of vegetable stock cubes.', 'https://www.themealdb.com/images/ingredients/Stock.png', 'Pantry'),
('Gravy Granules', 'Tub of gravy granules.', 'https://www.themealdb.com/images/ingredients/Gravy.png', 'Pantry'),
('Tinned Tomatoes', 'Can of chopped tomatoes.', 'https://www.themealdb.com/images/ingredients/Canned%20Tomatoes.png', 'Pantry'),
('Baked Beans', 'Can of baked beans in tomato sauce.', 'https://www.themealdb.com/images/ingredients/Baked%20Beans.png', 'Pantry'),
('Spaghetti Hoops', 'Can of spaghetti hoops in tomato sauce.', 'https://www.themealdb.com/images/ingredients/Pasta.png', 'Pantry'),
('Hot Dogs', 'Jar of hot dogs in brine.', 'https://www.themealdb.com/images/ingredients/Sausages.png', 'Pantry'),
('Burgers', 'Pack of 4 beef burgers.', 'https://www.themealdb.com/images/ingredients/Beef.png', 'Meat & Seafood'),
('Sausages', 'Pack of 8 pork sausages.', 'https://www.themealdb.com/images/ingredients/Sausages.png', 'Meat & Seafood'),
('Bacon', 'Pack of rashers of back bacon.', 'https://www.themealdb.com/images/ingredients/Bacon.png', 'Meat & Seafood'),
('Ham', 'Pack of sliced ham.', 'https://www.themealdb.com/images/ingredients/Ham.png', 'Meat & Seafood'),
('Salami', 'Pack of sliced salami.', 'https://www.themealdb.com/images/ingredients/Salami.png', 'Meat & Seafood'),
('Chorizo', 'Ring of chorizo.', 'https://www.themealdb.com/images/ingredients/Chorizo.png', 'Meat & Seafood'),
('Prawns', 'Bag of cooked and peeled prawns.', 'https://www.themealdb.com/images/ingredients/Prawns.png', 'Meat & Seafood'),
('Mussels', 'Bag of fresh mussels.', 'https://www.themealdb.com/images/ingredients/Mussels.png', 'Meat & Seafood'),
('Squid', 'Bag of frozen squid rings.', 'https://www.themealdb.com/images/ingredients/Squid.png', 'Frozen'),
('Fish Cakes', 'Pack of 2 cod fish cakes.', 'https://www.themealdb.com/images/ingredients/Fish.png', 'Frozen'),
('Spring Rolls', 'Pack of 10 vegetable spring rolls.', 'https://www.themealdb.com/images/ingredients/Spring%20Rolls.png', 'Frozen'),
('Samosas', 'Pack of 4 vegetable samosas.', 'https://www.themealdb.com/images/ingredients/Samosas.png', 'Frozen'),
('Onion Bhajis', 'Pack of 4 onion bhajis.', 'https://www.themealdb.com/images/ingredients/Onion.png', 'Frozen'),
('Pakoras', 'Pack of vegetable pakoras.', 'https://www.themealdb.com/images/ingredients/Chicken.png', 'Frozen'),
('Coleslaw', 'Tub of coleslaw.', 'https://www.themealdb.com/images/ingredients/Cabbage.png', 'Pantry'),
('Potato Salad', 'Tub of potato salad.', 'https://www.themealdb.com/images/ingredients/Potatoes.png', 'Pantry'),
('Hummus', 'Tub of hummus.', 'https://www.themealdb.com/images/ingredients/Hummus.png', 'Pantry'),
('Guacamole', 'Tub of guacamole.', 'https://www.themealdb.com/images/ingredients/Avocado.png', 'Pantry'),
('Dips', 'Selection of dips.', 'https://www.themealdb.com/images/ingredients/Sour%20Cream.png', 'Pantry'),
('Olives', 'Jar of green olives.', 'https://www.themealdb.com/images/ingredients/Olives.png', 'Pantry'),
('Sun-Dried Tomatoes', 'Jar of sun-dried tomatoes in oil.', 'https://www.themealdb.com/images/ingredients/Tomatoes.png', 'Pantry'),
('Artichoke Hearts', 'Can of artichoke hearts in water.', 'https://www.themealdb.com/images/ingredients/Artichokes.png', 'Pantry');