# PRICE SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  namespace: grocersave-dev
spec:
  selector:
    matchLabels: app: price-service
  template:
    metadata:
      labels: app: price-service
    spec:
      containers:
      - name: price-service
        image: grocersave/price-service:latest
        ports: [{containerPort: 8182}]
        env:
        - {name: PORT, value: "8182"}
        - {name: CASSANDRA_HOST, value: "cassandra"}
        - {name: RABBITMQ_HOST, value: "rabbitmq"}
---
apiVersion: v1
kind: Service
metadata:
  name: price-service
  namespace: grocersave-dev
spec:
  ports: [{port: 8182}]
  selector: app: price-service