apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: grocersave-dev
type: Opaque
data:
  # The values are Base64 encoded.
  # POSTGRES_USER: "grocer_admin" -> Z3JvY2VyX2FkbWlu
  # POSTGRES_PASSWORD: "dev_secret_123" -> ZGV2X3NlY3JldF8xMjM=
  # POSTGRES_DB: "grocersave_db" -> Z3JvY2Vyc2F2ZV9kYg==
  POSTGRES_USER: "Z3JvY2VyX2FkbWlu"
  POSTGRES_PASSWORD: "ZGV2X3NlY3JldF8xMjM="
  POSTGRES_DB: "Z3JvY2Vyc2F2ZV9kYg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
  namespace: grocersave-dev
type: Opaque
data:
  # RABBITMQ_DEFAULT_USER: "user" -> dXNlcg==
  # RABBITMQ_DEFAULT_PASS: "password" -> cGFzc3dvcmQ=
  RABBITMQ_DEFAULT_USER: "dXNlcg=="
  RABBITMQ_DEFAULT_PASS: "cGFzc3dvcmQ="

---
apiVersion: v1
kind: Secret
metadata:
  name: resend-creds
  namespace: grocersave-dev
type: Opaque
data: {}
