apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-daemon-config
  namespace: grocersave-dev
data:
  xray-daemon.yaml: |
    Version: 2
    Logging:
      LogLevel: "info"
    # Forward to localstack endpoint for k3d
    Endpoint: "http://host.k3d.internal:4566"
    # Bind to all interfaces inside the pod
    Socket:
      UDPAddress: "0.0.0.0:2000"
      TCPAddress: "0.0.0.0:2000"