# PRICE SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  namespace: grocersave-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      # Applying the DNS fix to the price service as well
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.100.0.10
        searches:
          - grocersave-dev.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"

      containers:
      - name: price-service
        image: grocersave/price-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8182
        env:
        - name: PORT
          value: "8182"
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: price-service
  namespace: grocersave-dev
spec:
  ports:
  - port: 8182
  selector:
    app: price-service