# 4. CASSANDRA (Price History) - StatefulSet for Data Persistence
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: grocersave-dev
spec:
  serviceName: "cassandra"
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        # Use your custom image from Docker Hub
        image: abumosameh/cassandra-grocersave:latest
        imagePullPolicy: Always # Ensures the latest image is always pulled
        ports:
        - containerPort: 9042
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "GrocerCluster"
        - name: CASSANDRA_DC
          value: "datacenter1"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: "GossipingPropertyFileSnitch"
        - name: HEAP_NEWSIZE
          value: "128M"
        - name: MAX_HEAP_SIZE
          value: "512M"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
  # This template creates a PersistentVolumeClaim for each pod.
  # The data will survive pod restarts.
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi # Request 10GB of storage
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: grocersave-dev
spec:
  ports:
  - port: 9042
  selector:
    app: cassandra
