# CATALOG SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: grocersave-dev
spec:
  selector:
    matchLabels: app: catalog-service
  template:
    metadata:
      labels: app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: grocersave/catalog-service:latest
        ports: [{containerPort: 8181}]
        env:
        - {name: PORT, value: "8181"}
        - {name: DB_HOST, value: "postgres"}
        - {name: ELASTIC_HOST, value: "elasticsearch:9200"}
        - {name: POSTGRES_USER, value: "grocer_admin"}
        - {name: POSTGRES_PASSWORD, value: "dev_secret_123"}
        - {name: POSTGRES_DB, value: "grocersave_db"}
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: grocersave-dev
spec:
  ports: [{port: 8181}]
  selector: app: catalog-service