# 2. POSTGRES (Catalog/Auth DB) - StatefulSet for Data Persistence
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: grocersave-dev
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        # Use your custom image from Docker Hub
        image: abumosameh/postgres-grocersave:latest
        imagePullPolicy: Always # Ensures the latest image is always pulled
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  # This template creates a PersistentVolumeClaim for each pod.
  # The data will survive pod restarts.
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi # Request 5GB of storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: grocersave-dev
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
