# 3. BFF SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  namespace: grocersave-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
      - name: bff-service
        image: grocersave/bff-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        resources:
          requests:
            cpu: "250m"
        env:
        - name: PORT
          value: "3100"
        - name: AUTH_URL
          value: "http://auth-service:8180"
        - name: CATALOG_URL
          value: "http://catalog-service:8181"
        - name: PRICE_URL
          value: "http://price-service:8182"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: "127.0.0.1:2000"
      - name: xray-daemon
        image: amazon/aws-xray-daemon:3.x
        command: ["/xray", "-c", "/etc/xray/xray-daemon.yaml"]
        ports:
          - containerPort: 2000
            protocol: UDP
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        volumeMounts:
          - name: xray-config-volume
            mountPath: /etc/xray
            readOnly: true
      volumes:
        - name: xray-config-volume
          configMap:
            name: xray-daemon-config

---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: grocersave-dev
spec:
  ports:
  - port: 3100
  selector:
    app: bff-service
